name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title:  '⚠ BREAKING CHANGES'
    labels:
      - 'break'
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🔧 Changes'
    labels:
      - 'change'
  - title: '🗑️ Removes'
    labels:
      - 'remove'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    label: 'chore'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
autolabeler:
  - label: 'enhancement'
    branch:
      - '/feature\/.+/'
      - '/feat\/.+/'
    body:
      - '/JIRA-[0-9]{1,4}/'
  - label: 'change'
    branch:
      - '/change\/.+/'
  - label: 'remove'
    branch:
      - '/remove\/.+/'
      - '/delete\/.+/'
  - label: 'chore'
    files:
      - '*.md'
    branch:
      - '/docs{0,1}\/.+/'
      - '/chore\/.+/'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
    title:
      - '/fix/i'
      - '/fixex/i'
  - label: 'break'
    branch:
      - '/break\/.+/'

template: |
  ## Changes

  $CHANGES